server:
  port: 80
  servlet:
    context-path: #/activiti
    session:
      timeout: 3000
      cookie:
        max-age: 3000
  tomcat:
    max-threads: 0
    uri-encoding: UTF-8

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.activiti.entity

spring:
#如果没有引入thymeleaf包，则需要添加该配置，ModelAndView的默认目录为resource里的static
#  mvc:
#      view:
#        prefix: /
#        suffix: .html

  datasource:
    url: jdbc:mysql://47.102.43.84:33061/activititest?serverTimezone=GMT&useSSL=false&characterEncoding=UTF-8&nullCatalogMeansCurrent=true
    username: root
    password: Changgongcheng00
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
      type: com.alibaba.druid.pool.DruidDataSource

  activiti:
    check-process-definitions: true #自动检查、部署流程定义文件
    database-schema-update: true #自动更新数据库结构
    #流程定义文件存放目录
    process-definition-location-prefix: classpath:/processes/
#    process-definition-location-suffixes: #流程文件格式
   #  - **.bpmn20.xml
   #  - **.bpmn

thymeleaf:
  cache: false

